  name: v4l2onvif
  version: git
  summary: v4l2 ONVIF 
  description: |
    * v4l2onvif :
    read from a V4L2 capture device and write to a V4L2 output device

  grade: stable 
  confinement: strict
  base: core18

  parts:
    v4l2onvif:
      plugin: make
      disable-parallel: true
      source: .
      source-type: git
      build-packages:
      - g++
      - make
      - cmake
      - pkg-config
      - autoconf 
      - automake 
      - libtool
      - gsoap 
      - libgsoap-dev 
      - libssl-dev
      - zlib1g-dev
      stage-packages:
      - libssl1.0
      - libgsoap-2.8

  apps:
    server:
      command: onvif-server.exe 
      daemon: simple
      plugs: [network-bind]

    client:
      command: onvif-client.exe 

