name: Release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: apt
      run: sudo apt-get install -y --no-install-recommends gsoap libgsoap-dev libssl-dev zlib1g-dev
    - name: make 
      run: make 
    - name: release
      uses: softprops/action-gh-release@v1
      with:
        files: onvif-server